### ISSUE TITLE
Crashes immediately on install

### ISSUE THREAD

**Issue by greysondn** [magmafoundation/Magma-1.15.x#80]
Crash log follows.

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 11/20/20 6:02 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Forge (forge) has failed to load correctly
§7null
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:184) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:777) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.15.2
        Minecraft Version ID: 1.15.2
        Operating System: Linux (amd64) version 4.15.0-112-generic
        Java Version: 1.8.0_252, Private Build
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
        Memory: 1348372440 bytes (1285 MB) / 2504523776 bytes (2388 MB) up to 7635730432 bytes (7282 MB)
        CPUs: 12
        JVM Flags: 2 total; -Xms1024M -Xmx8192M
        CraftBukkit Information:
   Running:
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
        at org.bukkit.Bukkit.getName(Bukkit.java:100)
        at org.bukkit.craftbukkit.v1_15_R1.CraftCrashReport.call(CraftCrashReport.java:23)
        at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:81)
        at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:73)
        at net.minecraft.crash.CrashReport.<init>(CrashReport.java:39)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:847)
        at java.lang.Thread.run(Thread.java:748)

        ModLauncher: 5.1.2+70+master.2845bb9
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services:
                /mixin-0.8.2.jar mixin PLUGINSERVICE
                /eventbus-2.2.0-service.jar eventbus PLUGINSERVICE
                /forge-1.15.2-31.2.45-b76ef2e.jar object_holder_definalize PLUGINSERVICE
                /forge-1.15.2-31.2.45-b76ef2e.jar runtime_enum_extender PLUGINSERVICE
                /accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE
                /forge-1.15.2-31.2.45-b76ef2e.jar capability_inject_definalize PLUGINSERVICE
                /forge-1.15.2-31.2.45-b76ef2e.jar runtimedistcleaner PLUGINSERVICE
                /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE
                /forge-1.15.2-31.2.45-b76ef2e.jar fml TRANSFORMATIONSERVICE
        FML: 31.2
        Forge: net.minecraftforge:31.2.45-b76ef2e
        FML Language Providers:
                javafml@31.2
                minecraft@1
        Mod List:
                forge-1.15.2-31.2.45-b76ef2e-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
                forge-1.15.2-31.2.45-b76ef2e-universal.jar Forge {forge@31.2.45-b76ef2e ERROR, magma@NONE CREATE_REGISTRIES}
        Magma:
   Running:
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
        at org.bukkit.Bukkit.getName(Bukkit.java:100)
        at org.bukkit.craftbukkit.v1_15_R1.CraftCrashReport.call(CraftCrashReport.java:23)
        at org.magmafoundation.magma.mod.MagmaMod.lambda$new$0(MagmaMod.java:41)
        at net.minecraftforge.fml.CrashReportExtender$1.call(CrashReportExtender.java:57)
        at net.minecraftforge.fml.CrashReportExtender$1.call(CrashReportExtender.java:50)
        at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:81)
        at net.minecraftforge.fml.CrashReportExtender.enhanceCrashReport(CrashReportExtender.java:40)
        at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:74)
        at net.minecraft.crash.CrashReport.<init>(CrashReport.java:39)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:847)
        at java.lang.Thread.run(Thread.java:748)

        Data Packs:
        Is Modded: ~~ERROR~~ NullPointerException: null
        Type: Dedicated Server (map_server.txt)
```

Booting via a script:

```bash
#!/bin/bash
java -Xms1024M -Xmx8192M -jar ./forge-1.15.2-31.2.45-b76ef2e.jar nogui
```

No mods installed. I run such things empty first to see how they'll behave.

**Comment by greysondn** [comment]
I'm going to close this issue.

That script was copied from my old server folder, but for some reason was incorrect.

> ```
>  #!/bin/bash
> java -Xms1024M -Xmx8192M -jar ./forge-1.15.2-31.2.45-b76ef2e.jar nogui
> ```

The issue comes with the last argument, `nogui`, which should instead be `--nogui`.

I do not feel intelligent. I'm sorry if I wasted any of your time.
