### ISSUE TITLE
[BUG] Server will not start.

### ISSUE THREAD

**Issue by MilkMGN** [magmafoundation/Magma-1.15.x#82]
**Describe the bug**
A clear and concise description of what the bug is: When running latest build from jenkins, tring to start the server will cause a crash.

**To Reproduce**
1. Install latest successful artifact from jenkins
2. try to run `java -jar forge-1.15.2-31.2.45-b76ef2e.jar`
3. see error

**Expected behavior**
Server runs

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: -
 - Mod Version: - 
 - Magma Version: latest?  
 - OS: windows

**Additional context**
Add any other context about the problem here:
console output:
```
PS C:\Users\Lenovo\Documents\Magma> java -jar forge-1.15.2-31.2.45-b76ef2e.jar
[09:27:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.2.45-b76ef2e, --fml.mcpVersion, 20200515.085601, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge]
[09:27:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 15.0.1 by AdoptOpenJDK
[09:27:58] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[09:27:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Lenovo/Documents/Magma/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
Exception in thread "main" [09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/NashornScriptEngineFactory
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.coremod.CoreModEngine.loadCoreMod(CoreModEngine.java:48)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.coremod.CoreModProvider.addCoreMod(CoreModProvider.java:12)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.fml.loading.LoadingModList.addCoreMods(LoadingModList.java:88)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:125)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1766)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.NashornScriptEngineFactory
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]:       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]:       at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[09:27:58] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]:       ... 35 more
```

**Comment by MilkMGN** [comment]
same result with nogui option

**Comment by MilkMGN** [comment]
build # is: Build #110 (Nov 5, 2020 12:27:43 PM)
